---
- name: "Check Hostname"
  hostname:
     name: "{{ hostname  }}"
  when:
     - inventory_hostname != "{{ hostname }}"

- name: "Set Timezone"
  timezone:
     name: "{{ timezone }}"


- name: "Install Postfix SMTP Server (Debian/Ubuntu)"
  apt:
     name: "postfix"
     state: "present"
  when: ansible_os_family == "Ubuntu" or  ansible_os_family == "Debian"

- name: "Remove Sendmail (RedHat/CentOS)"
  yum:
     name: "sendmail"
     state: "absent"
  when: ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"
 

- name: "Install Postfix SMTP Server (RedHat/CentOS)"
  yum:
     name: "postfix"
     state: "present"
  when: ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"


- name: "Change Mailname to Hostname"
  shell: echo "{{ hostname }}" > /etc/mailname

- name: "Install Mail Utilities (Debian/Ubuntu)"
  apt:
     name: "mailutils"
     state: "present"

  when: ansible_os_family == "Ubuntu" or  ansible_os_family == "Debian"

- name: "Install Mail utilits (RHEL/CentOS)"
  yum:
    name: "mailx"
    state: "present"
  when: ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"

- name: "Make Sure Firewall installed (Debian/Ubuntu)"
  apt:
     name: "ufw"
     state: present
  when: firewall and ansible_os_family == "Debian" or  ansible_os_family == "Ubuntu"

- name: "Make Sure Firewall installed (RedHat/CentOS)"
  yum:
     name: "firewalld"
     state: present
  when: firewall and ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"


- name: "Enable Firewall (Debian/Ubuntu)"
  service:
     name: "ufw"
     enabled: "yes"
  when: firewall and ansible_os_family == "Debian" or  ansible_os_family == "Ubuntu"


- name: "Enable Firewall"
  service:
     name: "firewalld"
     enabled: "yes"
  when: firewall and ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"

- name: "Add SMTP Rules rules (Debian/Ubuntu)"
  ufw:
     rule: allow
     proto: tcp
     src: "{{ loadbalancer_ip }}"
     port: 25
  when: firewall and ansible_os_family == "Debian" or  ansible_os_family == "Ubuntu"

- name: "Add SMTP Rules rules (RedHat/CentOS)"
  firewalld:
     state: enabled
     permanent: yes
     source: "{{ loadbalancer_ip }}"
     port: 25/tcp
  when: firewall and ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"

- name: "Add SSH Rule (Debian/Ubuntu)"
  ufw:
     rule: allow
     proto: tcp
     port: 22
  when: firewall and ansible_os_family == "Debian" or  ansible_os_family == "Ubuntu"

- name: "Add SSH Rule (RedHat/CentOS)"
  firewalld:
     state: enabled
     permanent: yes
     service: ssh
  when: firewall and ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"

- name: "Start Firewall (Debian/Ubuntu)"
  service:
     name: "ufw"
     state: "started"
  when: firewall and ansible_os_family == "Debian" or  ansible_os_family == "Ubuntu"

- name: "Start Firewall (RedHat/CentOS)"
  service:
     name: "firewalld"
     state: "started"
  when: firewall and ansible_os_family == "RedHat" or  ansible_os_family == "CentOS"

- name: "Generate Postfix configuration file"
  template:
     src: main.cf.j2
     dest: /etc/postfix/main.cf

- name: "Copy blacklisted_domains file"
  copy:
     src: secret/blacklisted_domains
     dest: /etc/postfix/blacklisted_domains
  when: outgoing_policy

- name: "Copy sender_access file"
  copy:
     src: secret/sender_access
     dest: /etc/postfix/sender_access
  when: outgoing_policy

- name: "Create postfix map file for blacklist domain"
  command: postmap /etc/postfix/blacklisted_domains
  when: outgoing_policy

- name: "Create postfix map file for sender_access"
  command: postmap /etc/postfix/sender_access
  when: outgoing_policy


- name: "Copy transport file"
  copy:
     src: secret/transport
     dest: /etc/postfix/transport
  when: rate_limit

- name: "Create postfix map file for transport file"
  command: postmap /etc/postfix/transport
  when: rate_limit

- name: "Generate Postfix master.cf configuration file"
  template:
     src: master.cf.j2
     dest: /etc/postfix/master.cf


- name: "Restart and Enable Postfix Service"
  service:
     name: "postfix"
     state: "restarted"
     enabled: "yes"

- name: "Configure OpenDKIM on Postfix"
  include: opendkim.yml
  when: opendkim

- name: "Configure rsyslog service on Server"
  include: rsyslog.yml
  when: rsyslog

- name: "Implement Monitoring scripts"
  include: monitoring.yml
  when: monitoring
